# Generated by Django 5.2.7 on 2025-10-30 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='job_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.jobmatch'),
        ),
        migrations.DeleteModel(
            name='JobMatch',
        ),
    ]
