# Generated by Django 5.2.7 on 2025-10-30 18:43

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_type', models.CharField(blank=True, choices=[('HOURLY', 'Hourly'), ('FIXED', 'Fixed')], default='', max_length=20)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('source_url', models.URLField(max_length=1000, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('experience_match', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VIEWED', 'Viewed'), ('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('INTERVIEWING', 'Interviewing'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.jobposting')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_proposal', models.TextField(blank=True, default='')),
                ('final_proposal', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('job_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_templates', to='jobs.jobmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
