# Generated by Django 5.2.7 on 2025-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
